name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Set up C/C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang-format

    - name: Build project
      run: make
    
    - name: Install Norminette
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install norminette

    - name: Check code with Norminette
      id: norminette
      run: |
        norminette > norminette_output.log
        grep -q "OK!" norminette_output.log || (echo "Norminette detected issues. Review the output." && cat norminette_output.log)

